### ISSUE TITLE
Scala Metals fails

### ISSUE THREAD

**Issue by mardukbp** [krassowski/jupyterlab-lsp#17]
Scala Metals is a language server that communicates over JSON-RPC. It can be installed with

```
curl -Lo coursier https://git.io/coursier-cli && chmod +x coursier
./coursier bootstrap org.scalameta:metals_2.12:0.7.0 -o metals -f`
```

The contents of my `servers.yml`:

```
langservers:
  scala:
    - /Users/marduk/metals
```

I launched Jupyter Lab as follows:

```
node miniconda3/share/jupyter/lab/staging/node_modules/jsonrpc-ws-proxy/dist/server.js --port 3000 --languageServers servers.yml 

jupyter lab
```

I created a Scala notebook (using the [Almond kerne](https://almond.sh/)l) and in `~/Library/Caches/org.scalameta.metals/global.log` I got the following error:

```
INFO  tracing is disabled for protocol LSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/marduk/Library/Caches/org.scalameta.metals/lsp.trace.json
INFO  Starting Metals server with configuration: MetalsServerConfig(
  bloop-protocol=BloopProtocol(auto),
  glob-syntax=GlobSyntaxConfig(uri),
  status-bar=StatusBarConfig(off),
  slow-task=SlowTaskConfig(off),
  execute-client-command=ExecuteClientCommandConfig(off),
  show-message=ShowMessageConfig(on),
  show-message-request=ShowMessageRequestConfig(on),
  no-initialized=false,
  compilers=PresentationCompilerConfigImpl(false,None,None,Map(scala/collection/mutable/ -> mutable., java/util/ -> ju.),Ascii,true,true,true,true,true,20,SECONDS),
  http=false,
  input-box=false,
  icons=none,
  statistics=StatisticsConfig(default)
)
INFO  logging to file /.metals/metals.log
Sep 01, 2019 9:45:07 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.nio.file.AccessDeniedException: /.metals
```

So it seems that Metals cannot create the directory `.metals` in the current workspace. I did some research and it appears that the workspace for the language server is set by `jsonrpc-ws-proxy/dist/server.js`.

Metals works in all the major editors, but it would be awesome to have it available in JupyterLab. See [Integrating a new editor](https://scalameta.org/metals/docs/editors/new-editor.html) for details.

**Comment by olafurpg** [comment]
What happens if you enable LSP tracing? It looks like the workspace rootUri provided in the “initialize” request is the root directory “/“, I would expect it to be a directory containing only the source code of the Jupyter notebooks.

**Comment by krassowski** [comment]
Hi there, thank you @mardukbp

**Comment by krassowski** [comment]
Hi there, thank you @mardukbp for reporting the issue and thanks @olafurpg for chiming in. Two quick notes:
- the JupyterLab does not expose the full path of the file in the server to the frontend extensions so it has to be passed around as a relative path, but the server proxy (`jsonrpc-ws-proxy/dist/server.js`) does not play well with it, even if started from the same directory.
I was experimenting with different `rootUri`s as a workaround, nothing seems to work (and therefore `rootUri may look strange).
- for that reason (but not only) the future versions of jupyterlab-lsp will be using a different approach  as outlined in #2 (instead of javascript-based `jsonrpc-ws-proxy`).

**Comment by olafurpg** [comment]
Would it be possible to create a temporary directory to host the workspace `rootUri`? Metals should work fine if the file contents is passed via text synchronization. We need the ability to create files/directories in the workspace to host logs and a small SQL database under `.metals/`.

**Comment by olafurpg** [comment]
Metals may crash on relative URIs since we generally assume file URIs are absolute. Another situation where we assume a file system is library dependency sources, which we write to the `.metals/readonly/` directory when users run "goto definition" on an external symbol.

**Comment by sbrunk** [comment]
I just gave this another shot with 0.6 and I think we're getting closer, as `rootUri` contains the path now.
```
INFO  logging to file /~/tmp/jupyterlab-lsp/.metals/metals.log
Nov 03, 2019 12:18:18 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.nio.file.FileSystemException: /~: Read-only file system
```
Unfortunately starting the path with `/~` still causes issues. I assume the `~` is supposed to be resolved to $HOME at some point. Any hints where it originates from?

**Comment by bollwyvl** [comment]
Yeah, the history of why the `~` even shows up is a bit odd: it's mostly cosmetic for a particular dialog in notebook classic, but is pretty painful in the language server context. 

At any rate, if you fired it up from basically anywhere _other_ than your home directory, it might work as-is. We should add an un-mangled, case normalized (because windows drive letters) canonical `rootUri` to the (as-yet unreleased, #81 and #90) server route which lists the servers. 

One thing that would help would be digging into the actual websocket messages in the network tab of the browser to see what the contents of the initialization message actually is.

**Comment by olafurpg** [comment]
To listen to incoming/outgoing JSON communication you can create the following file and restart Metals
```
~/Library/Caches/org.scalameta.metals/lsp.trace.json
```

**Comment by krassowski** [comment]
Probably related (but not 100% sure):

https://github.com/krassowski/jupyterlab-lsp/blob/92d2833c28632a7e66102ff597063b5ff68b92c8/packages/jupyterlab-lsp/src/index.ts#L73-L89

I think we need to resolve the root path in `jupyter-lsp` and get it with REST-like `/lsp` endpoint instead...

**Comment by sbrunk** [comment]
Thank you all for the pointers!
This is how `rootUri` looks in the init message:

```
[Trace - 08:11:28 AM] Received request 'initialize - (0)'
Params: {
  "processId": null,
  "rootUri": "file:///~/tmp/jupyterlab-lsp",
  ...
```

I tried starting jupyter lab from somewhere outside $HOME as suggested by @bollwyvl and it seems Metals is starting up normally. I can see it creating its startup files, there's LSP communication in `lsp.trace.json`, and the status bar says "fully initialized.

<img width="361" alt="grafik" src="https://user-images.githubusercontent.com/3939659/68086321-dc62ac80-fe4a-11e9-94cb-0631d6da0fa7.png">

We still don't get back anything really usable as most answers are empty.
```
[Trace - 06:58:41 PM] Sending notification 'textDocument/publishDiagnostics'
Params: {
  "uri": "file:///private/tmp/jupyter-lsp/scala.ipynb",
  "diagnostics": []
}
```
But I assume that's because Metals doesn't support Scala script files yet and has nothing to do with jupyterlab-lsp.

So I guess fully resolving `rootPath` on the server (#91) should solve the issue here.

**Comment by bollwyvl** [comment]
Thank you so much for continuing to fight with this! :crossed_swords: :shield: 

> Metals doesn't support Scala script files yet 

Yeah, we'll need to be able to generate virtual files for `ipynb.scala` (or whatever). this is where breaking up, normalizing, and handling per-language client features (#76 step 3) will come into play. This is as good an issue as any to start discussing it, but there's still a lot of work to do.

**Comment by sbrunk** [comment]
Since #92 has been merged, I just tried again using a dev build on master.
I get a fully resolved path under $HOME now and Metals starts up fine! 🎉 

Thanks for the fast fix! I guess this issue can be closed now.

**Comment by pietrodimarco91** [comment]
Regarding:
`Metals doesn't support Scala script files yet`

Do you think it is possible to "fallback" in Ammonite as it happens in VS?
