### ISSUE TITLE
ipynb_checkpoints suggest in pandas

### ISSUE THREAD

**Issue by Xetd71** [krassowski/jupyterlab-lsp#198]
## Description

The annoying suggest: 'ipynb_checkpoints/' every time I type dot ('.') in pandas dataframe
IMPORTANT: I am not press tab key at all

## Reproduce

Video example:
https://imgur.com/IFVJ0aD

## Context

- Operating System and version: Ubuntu 18.04
- JupyterLab version: 1.2.6
- `@krassowski/jupyterlab-lsp` version: 0.7.1

**Comment by Xetd71** [comment]
this bug is difficult to reproduce

**Comment by we-taper** [comment]
I had the same issue as well!

**Comment by data-coder** [comment]
Same issue here, it makes jupyterlab-lsp less usable. Any chance to reopen this issue? @Xetd71

**Comment by krassowski** [comment]
What version do you use?

**Comment by krassowski** [comment]
I am very sorry, but I think that reopening this issue is wrong. This issue describes a bug in a very old version and it does not help me to help you if you just reopen it. Instead, it would greatly help if you opened a new issue and provided reproducible example and you environment information (i.e. which version of JupyterLab and the extension do you use).

To reiterate, I cannot help without having the [bug report template](https://github.com/krassowski/jupyterlab-lsp/issues/new?template=bug_report.md) filled in. The template asks for information that we need in order to be able to help you. We know that this is a big ask, but this helps us diagnose issues quicker and gives us more time to improve this extension. If you have a problem filling it, please let us know and we will try to help (or improve the template if needed).

**Comment by vnemiro** [comment]
I had the same issue, but it was only on old versions.
I don't have this autocomplete problem after update `@krassowski/jupyterlab-lsp` to version 2.0.0

**Comment by Xetd71** [comment]
I apologize, I fell for the comments without understanding the problem.

The bug on my machine is not reproducible on version 2.0.0
