### ISSUE TITLE
Latest release on pypi is 0.8

### ISSUE THREAD

**Issue by andaag** [krassowski/jupyterlab-lsp#226]
I see 1.0 is out 👍😀, but the latest release on pypi is 0.8.

https://pypi.org/project/jupyter-lsp/#history

**Comment by bollwyvl** [comment]
Thanks for asking!

The npm 1.0 just means "works with jupyter lab 2", and is not meant to
signal anything special: we wanted major version releases of several
components for npm to avoid any conflicts.

No server changes were required to support the transition to jupyter lab 2,
so we didn't do a release on pip.

An 0.8.1, 0.9.0, or 1.0.0 server piece will be come in its own time, depending
on how much we break backwards compatibility.

**Comment by krassowski** [comment]
This is because `jupyter-lsp` did not change and a new version was not planned to be released just yet. We did not have to update the python backend to accommodate changes in frontend (related to JupyterLab 2.0 release). You can (and should) use `jupyter-lsp` 0.8 with `jupterlab-lsp` 1.0.

`jupyter-lsp`: pypi
`jupyterlab-lsp`: npm

**Comment by andaag** [comment]
Perfect, sorry about the confusion!
