### ISSUE TITLE
Develop Extension Against JupyterLab Local Dev Branch

### ISSUE THREAD

**Issue by edzkite** [krassowski/jupyterlab-lsp#233]
## What I am trying to do...
I'd like to test some changes on the extension on top of a modified version of JupyterLab locally. From their [official documentation](https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html#extension-authoring), `jlpm run add:sibling` seems to be the way to go about it. However, upon running `jlpm run add:sibling <local path to lsp extension>`, `jupyter build` no longers works.

## How I would like to learn how to do it...

What would be the best workflow to locally test changes of the LSP extension against a local branch of JupyterLab?

**Comment by bollwyvl** [comment]
That's a doozy. We've barely been able to keep up with the published
versions, much less trying to work with master (+).

I guess if you have some more logs, that might help, but it might just not
be straightforward right now.

One of our intentions had been to get this code base to a PR-able state, so
will have to get there eventually... But there are a few more significant
bridges to cross, namely of adopting more core dx conventions, breaking up
more functionality into pluggable pieces, etc.

**Comment by krassowski** [comment]
I cannot help straight away either, but https://github.com/jupyterlab/jupyterlab/pull/8037 might help; seems to be active. Also, have a look at https://github.com/jupyterlab/jupyterlab/issues/7468. Finally, the [JupyterLab gitter](https://gitter.im/jupyterlab/jupyterlab) may be the best place to ask a question like this if the `jupyter build` fail is not extension-specific (I did not run into this problem, but again I was not developing against JupyterLab master since 1.0).

**Comment by edzkite** [comment]
Thanks! I'll take a look at the links you gave.
