### ISSUE TITLE
Jump to definition is not working

### ISSUE THREAD

**Issue by kiranik** [krassowski/jupyterlab-lsp#275]
## Jump to definition is not working

Jump to definition option is not working for modules and packages.
When we use 'Jump to definition' option for an imported module or a package, nothing happens. It shows the following error in JS console.
```No jump targets found
Uncaught (in promise) TypeError: Cannot destructure property 'uri' of 'n' as it is undefined.
```
## Reproduce

1. Create a file named abcd.py with a class named sample
2. open a notebook
3. Import class sample from abcd
4. try to jump to the definition of sample class by selecting from menu or using Command+B

## Expected behavior

Open definition in a separate editor window.
## Context

- JupyterLab version:2.0.0
- python version - 3.7.4
- jupyterlab-lsp version - 1.0.0
- python-language-server - 0.30.0

<details><summary>Required: installed server extensions</summary>
<pre>
 jupyter_lsp  enabled 
    - Validating...
      jupyter_lsp 0.8.0 OK
 jupyterlab  enabled 
    - Validating...
      jupyterlab 2.0.0 OK
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
JupyterLab v2.0.0
Known labextensions:
   app dir: <path>
        @krassowski/jupyterlab-lsp v1.0.0  enabled  OK
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
```No jump targets found
Uncaught (in promise) TypeError: Cannot destructure property 'uri' of 'n' as it is undefined.```
</pre>
</details>

**Comment by krassowski** [comment]
Thank you for reporting this. I tried to reproduce this in two separate JupyterLab installations but it worked well in both cases for me: 

![it-is-working-jump-to-def-in-lsp](https://user-images.githubusercontent.com/5832902/83970702-01326d00-a8cf-11ea-9904-4e2d9630b8eb.gif)

Confirmed that it is working using
- JupyterLab v2.1.4,
- @krassowski/jupyterlab-lsp v1.0.0,
- jupyter-lsp==0.8.0
- python-language-server==0.33.1

as well as:
- JupyterLab v2.1.3,
- @krassowski/jupyterlab-lsp v1.0.0,
- jupyter-lsp==0.8.0
- python-language-server==0.31.9

I note that you use quite older versions of JupterLab and of the python-language-server. I would recommend you to update, as there were multiple changes in the JupyterLab since. Please feel free to reopen if you can reproduce the problem after updating.
