### ISSUE TITLE
Support Restarting jupyterlab-lsp

### ISSUE THREAD

**Issue by dclong** [krassowski/jupyterlab-lsp#283]
## Elevator Pitch

Provide a way to restart jupyterlab-lsp.

## Motivation

1. this enables users to install jupyterlab-lsp in a running Docker container environment. Users don't always have to option to rebuild images.
2. Some times jupyterlab-lsp crashes/freezes. It helps if can just restart jupyterlab-lsp instead of restarting the whole jupyterlab service (or Docker container if running in Docker).

**Comment by bollwyvl** [comment]
The backend part, Jupyter-lsp, is an extension to the notebook server. Are
you trying to restart:

- the notebook server that hosts jupyter-lsp
- language server processes managed by jupyter-lsp

If the latter, we have several existing issues open that are more
descriptive: #268, #237

If the former: we will need more information, as that sounds pretty bad,
and should be fixed rather than patched over.

To the larger issue:  We're definitely interested in this working in
docker, but like any other tool, Docker isn't a magic bullet, and for
interactive work has plenty of limitations.

**Comment by dclong** [comment]
I'm talking about restart lsp instead of the notebook server. Seems that this is a dups. Will close it.
