### ISSUE TITLE
Autocomplete not working, LSP bar does not show in JupyterLab

### ISSUE THREAD

**Issue by SWBZA** [krassowski/jupyterlab-lsp#395]
Hi.

1 - There is no "LSP button" at the bottom of the JupyterLab browser screen.
2 - I use Anaconda on a MacBook.
3 - jedi version 0.17.1
4 - jupyter-lsp version 0.9.2
5 - python-language-server version 0.35.1
6 - python version 3.8.3

All the above show in Anaconda in the environment.

Also in JupyterLab, extensions show and are enabled:
- @krassowski/jupyterlab-lsp
- @krassowski/theme-vscode
- @ryantam626/jupyterlab_code_formatter

Screen shots attached for all above.

What does not work: when I type, there is no auto-complete.  However, when I press <tab>, the suggestions show up.

Please help.  I've read and searched, but to no avail.

Thanks in advance,
Schalk
![extensions in JL](https://user-images.githubusercontent.com/34982917/97705940-8bb57c00-1abd-11eb-9246-bfffb917650e.png)
<img width="502" alt="Jedi" src="https://user-images.githubusercontent.com/34982917/97705948-8ce6a900-1abd-11eb-8957-6c79f2b56bb2.png">
<img width="488" alt="jupyter-lsp" src="https://user-images.githubusercontent.com/34982917/97705950-8d7f3f80-1abd-11eb-8204-f850f7a70a88.png">
<img width="479" alt="language server" src="https://user-images.githubusercontent.com/34982917/97705955-8e17d600-1abd-11eb-9789-90ed4c4d34b6.png">
![No autocomplete](https://user-images.githubusercontent.com/34982917/97705957-8eb06c80-1abd-11eb-90d2-3ecc89682c8d.png)
![No LSP bar](https://user-images.githubusercontent.com/34982917/97705960-8f490300-1abd-11eb-8313-80a2d74b35d8.png)
![With tab](https://user-images.githubusercontent.com/34982917/97705963-8f490300-1abd-11eb-9223-7bf39d26cde2.png)

**Comment by krassowski** [comment]
Thank you for opening this issue :tulip:. I read it carefully but unfortunately, I cannot help much without having the [bug report template](https://github.com/krassowski/jupyterlab-lsp/issues/new?template=bug_report.md) filled in. It appears that you might have chosen a different template, or deleted it.

The template asks for information that we need in order to be able to help you. We know that this is a big ask, but this helps us diagnose issues quicker and gives us more time to improve this extension. If you have a problem filling it, please let us know and we will try to help (or improve the template if needed).

I appreciate the screenshots, but this is not enough. We need the command line output in debug mode and the browser console information. Thank you. The suggestions that you see are the default JupyterLab suggestions - this indicates that the LSP is not properly installed. Did you restart the JupyterLab after installing jupyter-lsp? Can you import `jupyter_lsp` in your notebook?
