### ISSUE TITLE
Does not work if browser is running on a different machine than jupyterlab server.

### ISSUE THREAD

**Issue by robertgithub99** [krassowski/jupyterlab-lsp#40]
If you start the lsp server and jupyter lab with --no-browser --ip=ip_address_of_server_machine

And then you connect from a browser running on the same machine, it works fine. But if you run the browser on another machine it doesn't work.

**Comment by krassowski** [comment]
Thanks for reporting it. It should be fixed in the next version (0.6.0). I will let you know once the first beta is released.

**Comment by richardso21** [comment]
Any update w/ this? I also have the same issue with @robertgithub99, since I run jupyterlab through a server via `jupyter lab --no-browser --port=####`, which is a must for me. Features are pretty wonky, especially autocompletion at '.', which seems to not work at all. Any help would be appreciated.

**Comment by krassowski** [comment]
@robertgithub99 this should be resolved in the latest stable version. Would you mind checking the latest release (or the pre-release of 0.7.0)?

**Comment by robertgithub99** [comment]
Fixed in 0.6.0b0. Thanks
