### ISSUE TITLE
danger blank lab after installing lsp

### ISSUE THREAD

**Issue by badiku** [krassowski/jupyterlab-lsp#425]
tried all 3 steps of installing lsp, with no error

then start jupyterlab, everything disappeared!

no menu, no left pane, no tool bar. just a blank page at url localhost:8888/lab

then uninstall lsp extension, everything back!

amazing

**Comment by krassowski** [comment]
Thank you for opening this issue :tulip:. I read it carefully but unfortunately, I cannot help much without having the [bug report template](https://github.com/krassowski/jupyterlab-lsp/issues/new?template=bug_report.md) filled in. It appears that you might have chosen a different template, or deleted it.

In your case the problem might be as simple as the JupyterLab build not being completed before you tried to refresh the page. It would certainly greatly help other users if you could please provide the output from the developer console in your browser - please visit the [this MDN documentation chapter](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools#How_to_open_the_devtools_in_your_browser) to learn how to open it.

The template asks for information that we need in order to be able to help you. We know that this is a big ask, but this helps us diagnose issues quicker and gives us more time to improve this extension. If you have a problem filling it, please let us know and we will try to help (or improve the template if needed).

**Comment by krassowski** [comment]
It appears that a recent release of one of packages that we depend on may have broken some jupyterlab extensions on Python<3.8. It seems that a simple work-around of installing `typing_extensions` (e.g. `pip install typing_extensions` - or via conda if you use it) solves the problem. Sorry about subpar first experience, I can only assure you that this is a very new issue, as we test this extension before and after the release and the builds were passing seamlessly at that time. I also installed the newest version today morning and it was working fine.

Please do let us know if this solves your issue.

**Comment by krassowski** [comment]
I'm closing this issue as the `typing_extensions` dependency issue is now resolved; it seems to have arisen due to the conda package for `importlib_metadata` missing `typing_extensions`. If it does not work for you please provide the necessary information in the template.

**Comment by krassowski** [comment]
@badiku see also #428. It seems that you may have installed a very outdated version of the extension.
