### ISSUE TITLE
curious problem with Jupyter_lsp on PyPy3

### ISSUE THREAD

**Issue by stonebig** [krassowski/jupyterlab-lsp#610]
Trying Jupterlab on pypy3.7-v7.3.5-win64.zip, I get this strange message, I'm not sure what the problem is, if it's Jupyter_lsp or PyPy

Can you give me a direction per looking at the error message ?

![image](https://user-images.githubusercontent.com/4312421/120097318-1c296d00-c130-11eb-95a1-34a51a60ec50.png)

**Comment by mattip** [comment]
This is the same error message as in #608, but maybe not connected

**Comment by stonebig** [comment]
well, I forgot Jupyter_lsp is about tooltip.

It works but gets a big 1' to get fully ready

![image](https://user-images.githubusercontent.com/4312421/120101459-85b47600-c146-11eb-8298-6c8bcca7c541.png)

**Comment by krassowski** [comment]
`OSError: [Errno 22] Invalid argument` is a very unspecific way of Python telling us that the pipe has broken in a way because the LSP server crashed for some reason. I cannot see any traceback on the screenshot above (which is strange, though not impossible), and given that it works otherwise it is hard to guess what might be wrong.

**Comment by stonebig** [comment]
Thanks for the interpretation of that curious message. A crash makes more sense in the context where it happened
